name: notebooks2
channels:
  - conda-forge
  - conda 
  - pytorch
  - pypi
dependencies:
  - r-essentials
  - r-tensorflow
  - r-keras
  - r-boot
  - r-caret
  - r-learnr
  - r-rstan
  - r-brms
  - r-mlr
  - r-superlearner
  - r-caret
  - r-forecast
  - r-acepack
  - r-bcp
  - r-bdsmatrix
  - r-bestglm
  - r-bindrcpp
  - r-brglm
  - r-cairo
  - r-checkpoint
  - r-cvst
  - r-cvtools
  - r-ddalpha
  - r-deployrrserve
  - r-domc
  - r-drr
  - r-dt
  - r-emmeans
  - r-essentials
  - r-essentials-mrclient
  - r-fastica
  - r-fbasics
  - r-feather
  - r-fgarch
  - r-findpython
  - r-forge
  - r-formattable
  - r-fracdiff
  - r-fwdselect
  - r-gdata
  - r-getopt
  - r-ggvis
  - r-gss
  - r-guide
  - r-highcharter
  - r-hunspell
  - r-implyr
  - r-ipred
  - r-isocodes
  - r-janeaustenr
  - r-kohonen
  - r-leaps
  - r-lintr
  - r-logging
  - r-lsmeans
  - r-manipulate
  - r-microbenchmark
  - r-microsoftr
  - mkl_fft
  - mkl_random
  - r-mlmrev
  - r-mongolite
  - r-mrclient
  - r-mrclient-mlm
  - r-mrclient-mml
  - mro
  - mro-base
  - mro-impl
  - mro-basics
  - r-networkd3
  - nlopt-static
  - r-nloptr
  - r-nmf
  - numpy
  - numpy-base
  - numpy-devel
  - r-nycflights13
  - r-odbc
  - r-pdftools
  - r-perm
  - r-pki
  - r-plm
  - r-pls
  - r-polspline
  - r-pool
  - r-proc
  - r-profilemodel
  - r-profvis
  - r-qvcalc
  - libgcc
  - gxx_linux-64
  - python                          
  - pip
  - pandas-profiling
  - plotly
  - jupyterlab-plotly-extension
  - rpy2                         
  - rsa                           
  - scikit-image                  
  - scikit-learn 
  - sklearn-pandas        
  - dask
  - pandas-datareader             
  - pandas-gbq                    
  - pandocfilters 
  - tensorboard                   
  - tensorboard-plugin-wit        
  - tensorflow                    
  - tensorflow-datasets           
  - tensorflow-estimator          
  - tensorflow-hub                
  - tensorflow-metadata           
  - tensorflow-probability        
  - torchtext                     
  - torchvision                   
  - tornado   
  - Keras                         
  - Keras-Preprocessing           
  - matplotlib                    
  - matplotlib-venn
  - plotly
  - pycountry
  - scipy                         
  - scs                           
  - seaborn
  - statsmodels==0.12.1
  - nbconvert                     
  - nbformat                      
  - nest-asyncio                  
  - networkx                      
  - nibabel                       
  - nltk                          
  - notebook                      
  - numba                         
  - numexpr                       
  - numpy                         
  - oauth2client                  
  - oauthlib      
  - pytorch